acc: FOCO_taiwan #帳號
pw: Tony0101  #密碼
email: verena@foco.com.tw #寄送地址
timeout: 60 #等待時間

data: 
  select_from: '' #出港(請勿填寫)
  select_to: ''  #入港(請勿填寫)
  select_date: ''  #日期(免填)
  Commodity: Cotton, textiles
  Container_type: 40 dry high

windows: True #是否顯示視窗(目前測試此網站如不顯示視窗會無法爬取資料)

From: #出港(請依序填寫)
  - Shanghai
  - Ningbo
  - ab
  
To: # 入港(請依序填寫)
  - Durban
  - Itapoa
  - ab

login: False #登入狀態(請勿修改)